name: Test
on: push

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Deno
              uses: denolib/setup-deno@v2
              with:
                  deno-version: v1.x
            - name: Install dependencies
              run: |
                  pnpm ci
                  pnpm run build --if-present
            - name: Run tests
              run: |
                  pnpm run test
